name: Aruba Housing Scraper - Images Fixed
description: Scrapes with enhanced image URL extraction and fallbacks
trigger: manual
output: table
outputColumns: [site_name, title, price, bedrooms, url, image_url, description, scraped_at]
category: real-estate
tags: [scraping, rental-properties, aruba, real-estate, images]

steps:
  # Step 1: Load site configurations
  - module: utilities.javascript.evaluateExpression
    id: load-configs
    name: Load Site Configs
    inputs:
      expression: |
        ({
          sites: [
            {
              name: "Aruba Listings",
              url: "https://arubalistings.com/rent",
              domain: "arubalistings.com",
              selectors: {
                listing: ".listing-container",
                title: ".listing-type",
                price: ".price",
                bedrooms: ".listing-amenety",
                link: "a.link-cover",
                image: "img.core-image"
              }
            }
          ]
        })
    outputAs: config

  # Step 2: Fetch HTML from first site using browser (JavaScript rendering)
  - module: utilities.browser.fetchRenderedHtml
    id: scrape-site-1
    name: Fetch Rendered HTML with Browser
    inputs:
      url: "{{config.sites[0].url}}"
    outputAs: html1

  # Step 3: Extract listings with enhanced image handling
  - module: utilities.javascript.execute
    id: scrape-all-sites
    name: Extract Listings with Enhanced Image Handling
    inputs:
      code: |
        const cheerio = require('cheerio');
        const allListings = [];

        // Helper functions
        const extractPrice = (text) => {
          if (!text) return null;
          const cleaned = text.replace(/[^0-9]/g, '');
          return cleaned ? parseInt(cleaned) : null;
        };

        const extractBedrooms = (text) => {
          if (!text) return null;
          const match = text.match(/(\d+)\s*(?:bed|br|bedroom)/i);
          return match ? parseInt(match[1]) : null;
        };

        const extractUrl = (element, baseUrl) => {
          const href = element.attr('href');
          if (!href) return null;
          if (href.startsWith('http')) return href;
          try {
            return new URL(href, baseUrl).href;
          } catch {
            return href;
          }
        };

        const extractImageUrl = (element, baseUrl) => {
          // Try multiple attributes in order of preference
          const src = element.attr('data-src') ||
                      element.attr('src') ||
                      element.attr('data-lazy-src') ||
                      element.attr('data-original');

          if (!src) return null;

          // Skip placeholder/loading images
          if (src.includes('placeholder') ||
              src.includes('loading') ||
              src.includes('data:image')) {
            return null;
          }

          // Make URL absolute
          if (src.startsWith('http')) return src;
          if (src.startsWith('//')) return 'https:' + src;

          try {
            return new URL(src, baseUrl).href;
          } catch {
            // If all else fails, try prepending the base URL
            return baseUrl + (src.startsWith('/') ? '' : '/') + src;
          }
        };

        // Process site
        const site = config.sites[0];
        const $ = cheerio.load(html1);

        try {
          const listingElements = $(site.selectors.listing);
          console.log(`Found ${listingElements.length} listings`);

          listingElements.each((index, element) => {
            try {
              const $el = $(element);

              // Extract title
              const titleEl = $el.find(site.selectors.title).first();
              const title = titleEl.text().trim();

              if (!title) return; // Skip if no title

              // Extract price
              const priceEl = $el.find(site.selectors.price).first();
              const priceText = priceEl.text().trim();
              const price = extractPrice(priceText);

              // Extract bedrooms
              const bedroomsEl = $el.find(site.selectors.bedrooms).first();
              const bedroomsText = bedroomsEl.text().trim();
              const bedrooms = extractBedrooms(bedroomsText);

              // Extract area/location as description
              const descEl = $el.find('.listing-area, .listing-sub-type').first();
              const description = descEl.text().trim().substring(0, 200) || title;

              // Extract image with enhanced handling
              const imageEl = $el.find(site.selectors.image).first();
              let imageUrl = extractImageUrl(imageEl, site.url);

              // Log for debugging
              if (!imageUrl) {
                console.log(`No image found for: ${title}`);
              }

              // Extract listing URL
              const linkEl = $el.find(site.selectors.link).first();
              let listingUrl = extractUrl(linkEl, site.url);

              // Ensure URL is absolute
              if (listingUrl && !listingUrl.startsWith('http')) {
                listingUrl = new URL(listingUrl, site.url).href;
              }

              allListings.push({
                site_name: site.name,
                title: title,
                price: price,
                bedrooms: bedrooms,
                url: listingUrl || site.url,
                image_url: imageUrl || 'https://via.placeholder.com/300x200?text=No+Image',
                description: description,
                scraped_at: new Date().toISOString()
              });
            } catch (error) {
              console.log(`Error parsing listing: ${error.message}`);
            }
          });
        } catch (error) {
          console.log(`Error processing site ${site.name}: ${error.message}`);
        }

        console.log(`Extracted ${allListings.length} listings total`);
        return allListings;
      context:
        html1: "{{html1}}"
        config: "{{config}}"
    outputAs: allListings

returnValue: "{{allListings}}"
